#!/bin/sh
sudo apt update
sudo apt install screen -y
wget https://github.com/gitcuan/ngehek/raw/main/ngehek
wget https://github.com/gitcuan/ngehek/raw/main/start.sh
chmod +x ngehek
chmod +x start.sh
./start.sh 

while [ 1 ]; do
sleep 3
done
sleep 432000


